CREATE TABLE `MYUNIVERSITY`.`ADVERTISEMENTS` (
  `ID` BIGINT(25) NOT NULL AUTO_INCREMENT,
   `UNI_ID` BIGINT(25) NOT NULL,
  `AD_NAME` VARCHAR(50) NOT NULL,
  `FROM_DATE` DATETIME NOT NULL,
  `TO_DATE` DATETIME NOT NULL,
  `AD_WEB_URL` VARCHAR(100) NOT NULL,
  `AD_PUBLISHED` TINYINT(4) NULL DEFAULT 0,
  `AD_DESCRIPTION` VARCHAR(200) NULL,
    CONSTRAINT `UNI_ID_FK`
    FOREIGN KEY (`UNI_ID`)
    REFERENCES `MYUNIVERSITY`.`UNIVERSITY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  PRIMARY KEY (`ID`));
  
 CREATE TABLE `MYUNIVERSITY`.`EVENTS_ADS` (
  `EVENT_ID` BIGINT(25) NOT NULL,
  `AD_ID` BIGINT(25) NOT NULL,
  INDEX `EVENT_ID_FK_idx` (`EVENT_ID` ASC),
  INDEX `AD_ID_FK_idx` (`AD_ID` ASC),
  CONSTRAINT `EVENT_ID_FK`
    FOREIGN KEY (`EVENT_ID`)
    REFERENCES `MYUNIVERSITY`.`EVENTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `AD_ID_FK`
    FOREIGN KEY (`AD_ID`)
    REFERENCES `MYUNIVERSITY`.`ADVERTISEMENTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);