
CREATE TABLE `MYUNIVERSITY`.`SOCIAL_BADGE_POINTS` (
  `ID` BIGINT(25) NOT NULL AUTO_INCREMENT,
  `SOCIAL_BADGE_NAME` VARCHAR(45) NULL,
  `SOCIAL_BADGE_POINTS` INT(5) NULL,
  `UNIVERSITY_ID` BIGINT(25) NULL,
  PRIMARY KEY (`ID`),
  INDEX `uniID_idx` (`UNIVERSITY_ID` ASC),
  CONSTRAINT `uniID`
    FOREIGN KEY (`UNIVERSITY_ID`)
    REFERENCES `MYUNIVERSITY`.`UNIVERSITY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);