CREATE TABLE `MYUNIVERSITY`.`SOCIAL_BADGES` (
  `ID` BIGINT(25) NOT NULL AUTO_INCREMENT,
  `BADGE_NAME` VARCHAR(50) NULL,
  `BADGE_DESCRIPTION` VARCHAR(100) NULL,
  `NUMBER_OF_EVENTS` INT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE `MYUNIVERSITY`.`SOCIAL_BADGES_DEPARTMENTS` (
  `ID` BIGINT(25) NOT NULL AUTO_INCREMENT,
  `SOCIAL_BADGE_ID` BIGINT(25) NULL,
  `DEPARTMENT_ID` BIGINT(25) NULL,
  PRIMARY KEY (`ID`),
  INDEX `social_badge_id_idx` (`SOCIAL_BADGE_ID` ASC),
  INDEX `deparment_id_idx` (`DEPARTMENT_ID` ASC),
  CONSTRAINT `social_badge_id`
    FOREIGN KEY (`SOCIAL_BADGE_ID`)
    REFERENCES `MYUNIVERSITY`.`SOCIAL_BADGES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `deparment_id`
    FOREIGN KEY (`DEPARTMENT_ID`)
    REFERENCES `MYUNIVERSITY`.`DEPARTMENTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
  
 CREATE TABLE `MYUNIVERSITY`.`SPONSOR` (
  `ID` BIGINT(25) NOT NULL AUTO_INCREMENT,
  `SPONSOR_NAME` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`));
  
  CREATE TABLE `MYUNIVERSITY`.`EVENT_SPONSOR` (
  `ID` BIGINT(25) NOT NULL AUTO_INCREMENT,
  `EVENT_ID` BIGINT(25) NULL,
  `SPONSOR_ID` BIGINT(25) NULL,
  PRIMARY KEY (`ID`),
  INDEX `event_id_idx` (`EVENT_ID` ASC),
  INDEX `sponsor_id_idx` (`SPONSOR_ID` ASC),
  CONSTRAINT `event_id_sp`
    FOREIGN KEY (`EVENT_ID`)
    REFERENCES `MYUNIVERSITY`.`EVENTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sponsor_id`
    FOREIGN KEY (`SPONSOR_ID`)
    REFERENCES `MYUNIVERSITY`.`SPONSOR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

