









ALTER TABLE `MYUNIVERSITY`.`EVENT_SKILL_SCHEDULE` 
DROP FOREIGN KEY `EVENT11`;
ALTER TABLE `MYUNIVERSITY`.`EVENT_SKILL_SCHEDULE` 
CHANGE COLUMN `Event_ID` `EVENT_ID` BIGINT(25) NULL DEFAULT NULL ,
CHANGE COLUMN `Event_START_TIME` `EVENT_START_TIME` DATETIME NULL DEFAULT NULL ,
CHANGE COLUMN `Event_END_TIME` `EVENT_END_TIME` DATETIME NULL DEFAULT NULL ;
ALTER TABLE `MYUNIVERSITY`.`EVENT_SKILL_SCHEDULE` 
ADD CONSTRAINT `EVENT11`
  FOREIGN KEY (`EVENT_ID`)
  REFERENCES `MYUNIVERSITY`.`EVENTS` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


CREATE TABLE `MYUNIVERSITY`.`EVENT_SOCIAL_BADGE` (
  `ID` BIGINT(25) NOT NULL,
  `SOCIAL_BADGE_ID` BIGINT(25) NULL,
  `EVENT_ID` BIGINT(25) NULL,
  `DESCRIPTION` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`),
  INDEX `social_badge_id_idx` (`SOCIAL_BADGE_ID` ASC),
  INDEX `event_id_idx` (`EVENT_ID` ASC),
  CONSTRAINT `social_badge_id_fk`
    FOREIGN KEY (`SOCIAL_BADGE_ID`)
    REFERENCES `MYUNIVERSITY`.`SOCIAL_BADGES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `event_id_fkk`
    FOREIGN KEY (`EVENT_ID`)
    REFERENCES `MYUNIVERSITY`.`EVENTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

ALTER TABLE `MYUNIVERSITY`.`EVENT_SOCIAL_BADGE` 
CHANGE COLUMN `ID` `ID` BIGINT(25) NOT NULL AUTO_INCREMENT ;