CREATE TABLE `MYUNIVERSITY`.`LOBO_BADGES` (
  `ID` BIGINT(25) NOT NULL AUTO_INCREMENT,
  `LOBO_BADGE_NAME` VARCHAR(100) NULL,
  `EFFECTIVE_COMMUNICATION` VARCHAR(100) NULL,
  `EFFECTIVE_COMMUNICATION_MEDAL` BIGINT(25) NULL,
  `COLLABORATION` VARCHAR(100) NULL,
  `COLLABORATION_MEDAL` BIGINT(25) NULL,
  `CRITICAL_THINKING` VARCHAR(100) NULL,
  `CRITICAL_THINKING_MEDAL` BIGINT(25) NULL,
  `PROFESSIONALISM` VARCHAR(100) NULL,
  `PROFESSIONALISM_MEDAL` BIGINT(25) NULL,
  `REASEARCH_ANALYSIS` VARCHAR(100) NULL,
  `REASEARCH_ANALYSIS_MEDAL` BIGINT(25) NULL,
  PRIMARY KEY (`ID`),
  INDEX `EFFECTIVE_COMMU_idx` (`EFFECTIVE_COMMUNICATION_MEDAL` ASC),
  INDEX `COLLABORATION_idx` (`COLLABORATION_MEDAL` ASC),
  INDEX `CRITICAL_THINKING_idx` (`CRITICAL_THINKING_MEDAL` ASC),
  INDEX `PROFESSIONALISM_idx` (`PROFESSIONALISM_MEDAL` ASC),
  INDEX `RESEARCH_ANALYSIS_idx` (`REASEARCH_ANALYSIS_MEDAL` ASC),
  CONSTRAINT `EFFECTIVE_COMMU`
    FOREIGN KEY (`EFFECTIVE_COMMUNICATION_MEDAL`)
    REFERENCES `MYUNIVERSITY`.`SKILL_BADGES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `COLLABORATION`
    FOREIGN KEY (`COLLABORATION_MEDAL`)
    REFERENCES `MYUNIVERSITY`.`SKILL_BADGES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CRITICAL_THINKING`
    FOREIGN KEY (`CRITICAL_THINKING_MEDAL`)
    REFERENCES `MYUNIVERSITY`.`SKILL_BADGES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PROFESSIONALISM`
    FOREIGN KEY (`PROFESSIONALISM_MEDAL`)
    REFERENCES `MYUNIVERSITY`.`SKILL_BADGES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RESEARCH_ANALYSIS`
    FOREIGN KEY (`REASEARCH_ANALYSIS_MEDAL`)
    REFERENCES `MYUNIVERSITY`.`SKILL_BADGES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
    
    
    /*
-- Query: select * from LOBO_BADGES
LIMIT 0, 50000

-- Date: 2016-05-03 18:32
*/
INSERT INTO `LOBO_BADGES` (`ID`,`LOBO_BADGE_NAME`,`EFFECTIVE_COMMUNICATION`,`EFFECTIVE_COMMUNICATION_MEDAL`,`COLLABORATION`,`COLLABORATION_MEDAL`,`CRITICAL_THINKING`,`CRITICAL_THINKING_MEDAL`,`PROFESSIONALISM`,`PROFESSIONALISM_MEDAL`,`REASEARCH_ANALYSIS`,`REASEARCH_ANALYSIS_MEDAL`) VALUES (1,'Lobo Pup','6',1,'1',1,'3',1,'4',1,'3',1);
INSERT INTO `LOBO_BADGES` (`ID`,`LOBO_BADGE_NAME`,`EFFECTIVE_COMMUNICATION`,`EFFECTIVE_COMMUNICATION_MEDAL`,`COLLABORATION`,`COLLABORATION_MEDAL`,`CRITICAL_THINKING`,`CRITICAL_THINKING_MEDAL`,`PROFESSIONALISM`,`PROFESSIONALISM_MEDAL`,`REASEARCH_ANALYSIS`,`REASEARCH_ANALYSIS_MEDAL`) VALUES (2,'Lobo Scout','5',2,'4',2,'4',2,'3',2,'5',2);
INSERT INTO `LOBO_BADGES` (`ID`,`LOBO_BADGE_NAME`,`EFFECTIVE_COMMUNICATION`,`EFFECTIVE_COMMUNICATION_MEDAL`,`COLLABORATION`,`COLLABORATION_MEDAL`,`CRITICAL_THINKING`,`CRITICAL_THINKING_MEDAL`,`PROFESSIONALISM`,`PROFESSIONALISM_MEDAL`,`REASEARCH_ANALYSIS`,`REASEARCH_ANALYSIS_MEDAL`) VALUES (3,'Lobo','4',3,'4',3,'2',3,'3',3,'6',3);
INSERT INTO `LOBO_BADGES` (`ID`,`LOBO_BADGE_NAME`,`EFFECTIVE_COMMUNICATION`,`EFFECTIVE_COMMUNICATION_MEDAL`,`COLLABORATION`,`COLLABORATION_MEDAL`,`CRITICAL_THINKING`,`CRITICAL_THINKING_MEDAL`,`PROFESSIONALISM`,`PROFESSIONALISM_MEDAL`,`REASEARCH_ANALYSIS`,`REASEARCH_ANALYSIS_MEDAL`) VALUES (4,'Pak Leader','2',4,'1',4,'3',4,'4',4,'1',4);

