INSERT INTO `MYUNIVERSITY`.`EVENT_SKILLS` (`ID`, `EVENT_ID`, `SKILL_ID`) VALUES ('1', '1', '1');
INSERT INTO `MYUNIVERSITY`.`EVENT_SKILLS` (`ID`, `EVENT_ID`, `SKILL_ID`) VALUES ('2', '1', '3');
INSERT INTO `MYUNIVERSITY`.`EVENT_SKILLS` (`ID`, `EVENT_ID`, `SKILL_ID`) VALUES ('3', '1', '5');
INSERT INTO `MYUNIVERSITY`.`EVENT_SKILLS` (`ID`, `EVENT_ID`, `SKILL_ID`) VALUES ('4', '1', '4');
INSERT INTO `MYUNIVERSITY`.`EVENT_SKILLS` (`ID`, `EVENT_ID`, `SKILL_ID`) VALUES ('5', '1', '15');
INSERT INTO `MYUNIVERSITY`.`EVENT_SKILLS` (`ID`, `EVENT_ID`, `SKILL_ID`) VALUES ('6', '1', '10');
INSERT INTO `MYUNIVERSITY`.`EVENT_SKILLS` (`ID`, `EVENT_ID`, `SKILL_ID`) VALUES ('7', '1', '21');
INSERT INTO `MYUNIVERSITY`.`EVENT_SKILLS` (`ID`, `EVENT_ID`, `SKILL_ID`) VALUES ('8', '1', '25');
