INSERT INTO `MYUNIVERSITY`.`EVENT_TAGS` (`ID`, `EVENT_ID`, `TAG_ID`) VALUES ('1', '1', '2');
INSERT INTO `MYUNIVERSITY`.`EVENT_TAGS` (`ID`, `EVENT_ID`, `TAG_ID`) VALUES ('2', '1', '3');
INSERT INTO `MYUNIVERSITY`.`EVENT_TAGS` (`ID`, `EVENT_ID`, `TAG_ID`) VALUES ('3', '1', '5');
