INSERT INTO `MYUNIVERSITY`.`EVENT_INTERESTS` (`ID`, `EVENT_ID`, `INTEREST_ID`) VALUES ('1', '1', '1');
INSERT INTO `MYUNIVERSITY`.`EVENT_INTERESTS` (`ID`, `EVENT_ID`, `INTEREST_ID`) VALUES ('2', '1', '3');
