INSERT INTO `MYUNIVERSITY`.`SKILL_CATEGORIES` (`ID`, `CATEGORY_NAME`) VALUES ('1', 'Commmunication');
INSERT INTO `MYUNIVERSITY`.`SKILL_CATEGORIES` (`ID`, `CATEGORY_NAME`) VALUES ('2', 'Collabration');
INSERT INTO `MYUNIVERSITY`.`SKILL_CATEGORIES` (`ID`, `CATEGORY_NAME`) VALUES ('3', 'Critical Thinking');
INSERT INTO `MYUNIVERSITY`.`SKILL_CATEGORIES` (`ID`, `CATEGORY_NAME`) VALUES ('4', 'Research And Data');
INSERT INTO `MYUNIVERSITY`.`SKILL_CATEGORIES` (`ID`, `CATEGORY_NAME`) VALUES ('5', 'Professionalism');
