INSERT INTO `MYUNIVERSITY`.`TAGS` (`ID`, `TAG_NAME`) VALUES ('1', 'Family Friendly');
INSERT INTO `MYUNIVERSITY`.`TAGS` (`ID`, `TAG_NAME`) VALUES ('2', 'Free Parking');
INSERT INTO `MYUNIVERSITY`.`TAGS` (`ID`, `TAG_NAME`) VALUES ('3', 'Group Firendly');
INSERT INTO `MYUNIVERSITY`.`TAGS` (`ID`, `TAG_NAME`) VALUES ('4', 'Snacks Included');
INSERT INTO `MYUNIVERSITY`.`TAGS` (`ID`, `TAG_NAME`) VALUES ('5', 'Lunch Included');
INSERT INTO `MYUNIVERSITY`.`TAGS` (`ID`, `TAG_NAME`) VALUES ('6', 'No Food Allowed');
