CREATE TABLE `MYUNIVERSITY`.`UNIVERSITY` (
  `ID` BIGINT(25) NOT NULL AUTO_INCREMENT,
  `UNIVERSITY_NAME` VARCHAR(200) NULL,
  PRIMARY KEY (`ID`));


ALTER TABLE `MYUNIVERSITY`.`DEPARTMENTS` 

ADD COLUMN `UNIVERSITY_ID` BIGINT(25) NULL 
AFTER `VALID`,
ADD INDEX `UNIVERSITY_FK_idx` (`UNIVERSITY_ID` ASC);

ALTER TABLE `MYUNIVERSITY`.`DEPARTMENTS` 

ADD CONSTRAINT `UNIVERSITY_FK`
  FOREIGN KEY (`UNIVERSITY_ID`)
  
REFERENCES `MYUNIVERSITY`.`UNIVERSITY` (`ID`)
  
ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `MYUNIVERSITY`.`EVENTS` 

ADD COLUMN `UNIVERSITY_ID` BIGINT(25) NULL;
ALTER TABLE `MYUNIVERSITY`.`EVENTS` 
ADD CONSTRAINT `UNIVERSITY_EV_FK`
 
FOREIGN KEY (`UNIVERSITY_ID`)
  REFERENCES `MYUNIVERSITY`.`UNIVERSITY` (`ID`)
  
ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `MYUNIVERSITY`.`INTERESTS` 
ADD COLUMN `UNIVERSITY_ID` 
BIGINT(25) NULL AFTER `INTEREST_NAME`,

ADD INDEX `UNIVERSITY_IN_FK_idx` (`UNIVERSITY_ID` ASC);

ALTER TABLE `MYUNIVERSITY`.`INTERESTS` 
ADD CONSTRAINT `UNIVERSITY_IN_FK`
  
FOREIGN KEY (`UNIVERSITY_ID`)
  REFERENCES `MYUNIVERSITY`.`UNIVERSITY` (`ID`)
  
ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `MYUNIVERSITY`.`ROLES` 

ADD COLUMN `UNIVERSITY_ID` BIGINT(25) NULL 
AFTER `ROLE_NAME`,

ADD INDEX `UNIVERSITY_RO_FK_idx` (`UNIVERSITY_ID` ASC);

ALTER TABLE `MYUNIVERSITY`.`ROLES` 

ADD CONSTRAINT `UNIVERSITY_RO_FK`
  FOREIGN KEY (`UNIVERSITY_ID`)
  
REFERENCES `MYUNIVERSITY`.`UNIVERSITY` (`ID`)
  
ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `MYUNIVERSITY`.`SKILL_BADGES` 

ADD COLUMN `UNIVERSITY_ID` BIGINT(25) NULL 
AFTER `SKILL_BADGE_POINTS`,

ADD INDEX `UNIVERSITY_SB_FK_idx` (`UNIVERSITY_ID` ASC);

ALTER TABLE `MYUNIVERSITY`.`SKILL_BADGES` 

ADD CONSTRAINT `UNIVERSITY_SB_FK`
  FOREIGN KEY (`UNIVERSITY_ID`)
  
REFERENCES `MYUNIVERSITY`.`UNIVERSITY` (`ID`)
  
ON DELETE NO ACTION
  ON UPDATE NO ACTION;


ALTER TABLE `MYUNIVERSITY`.`SKILLS` 

ADD COLUMN `UNIVERSITY_ID` BIGINT(25) NULL 
AFTER `SKILL_CATEGORY_ID`,

ADD INDEX `UNIVERSITY_SK_FK_idx` (`UNIVERSITY_ID` ASC);

ALTER TABLE `MYUNIVERSITY`.`SKILLS` 

ADD CONSTRAINT `UNIVERSITY_SK_FK`
  FOREIGN KEY (`UNIVERSITY_ID`)
  
REFERENCES `MYUNIVERSITY`.`UNIVERSITY` (`ID`)
  
ON DELETE NO ACTION
  ON UPDATE NO ACTION;


ALTER TABLE `MYUNIVERSITY`.`TOP_LEVEL_BADGES` 

ADD COLUMN `UNIVERSITY_ID` BIGINT(25) NULL 
AFTER `TOP_BADGE_POINTS`,

ADD INDEX `UNIVERSITY_TLB_FK_idx` (`UNIVERSITY_ID` ASC);

ALTER TABLE `MYUNIVERSITY`.`TOP_LEVEL_BADGES` 

ADD CONSTRAINT `UNIVERSITY_TLB_FK`
  FOREIGN KEY (`UNIVERSITY_ID`)
  
REFERENCES `MYUNIVERSITY`.`UNIVERSITY` (`ID`)
  
ON DELETE NO ACTION
  ON UPDATE NO ACTION;


ALTER TABLE `MYUNIVERSITY`.`USERS` 

ADD COLUMN `UNIVERSITY_ID` BIGINT(25) NULL 
AFTER `USER_ROLE`,

ADD INDEX `UNIVERSITY_UR_FK_idx` (`UNIVERSITY_ID` ASC);

ALTER TABLE `MYUNIVERSITY`.`USERS` 

ADD CONSTRAINT `UNIVERSITY_UR_FK`
  FOREIGN KEY (`UNIVERSITY_ID`)
  
REFERENCES `MYUNIVERSITY`.`UNIVERSITY` (`ID`)
  
ON DELETE NO ACTION
  ON UPDATE NO ACTION;























