Alter table ADVERTISEMENTS 
ADD COLUMN `DATE_CREATED` datetime DEFAULT NULL,
ADD COLUMN `USER_CREATED` varchar(50) DEFAULT NULL,
ADD COLUMN `DATE_MODIFIED` datetime DEFAULT NULL,
ADD COLUMN `USER_MODIFIED` varchar(50) DEFAULT NULL;

update ADVERTISEMENTS set  DATE_CREATED=now() where  DATE_CREATED is null
update ADVERTISEMENTS set  DATE_MODIFIED=now() where  DATE_MODIFIED is null